#ifndef OE1_SHADER_ID_H_
#define OE1_SHADER_ID_H_


namespace OE1Core
{
	enum class ShaderID
	{
		INIF_GRID,
		MODEL_PREVIEW,
		OBJECT_OUTLINE,
		TEXTURE_2D_ARRAY_EXTRACTOR,
		VIEWPORT_BILLBOARD_ICON_TEXTURE_PASS,
		VIEWPORT_BILLBOARD_ICON_ID_PASS
	};
}

#endif // !OE1_SHADER_ID_H_
