#ifndef OE1_SHADER_ID_H_
#define OE1_SHADER_ID_H_


namespace OE1Core
{
	enum class ShaderID
	{
		INIF_GRID,
		OBJECT_OUTLINE,
		TEXTURE_2D_ARRAY_EXTRACTOR,
		VIEWPORT_BILLBOARD_ICON_TEXTURE_PASS,
		VIEWPORT_BILLBOARD_ICON_ID_PASS,
		SKYBOX,

		DEFFERED_LIGHT_PASS,
		BLOOM_PASS,

		// Preview
		MODEL_PREVIEW,
		MATERIAL_PREVIEW,
		SKY_DOM_PREVIEW,
		HDRI_PREVIEW,

		// IBL
		TO_CUBEMAP,
		TO_IRRADIANCEMAP,
		PREFILTERD_ENV_MAP,
		PRE_BRDF_MAP,

		// Bloom
		BLOOM_DOWN_SAMPLE,
		BLOOM_UP_SAMPLE,

		// Post-Process
		POST_PROCESS_BLOOM_MIX,
		POS_POROCESS_COLOR_BLEND,

		LOCAL_DEBUG_SHAPE,
		SCENE_DEBUG_SHAPE,
		PHYSICS_DEBUG_SHAPE,

		FULL_SCREEN_QUAD,
		FINAL_COLOR_BLEND


	};
}

#endif // !OE1_SHADER_ID_H_
